### ISSUE TITLE
Saidil on lahendatud varundamine väljaspool serverit (andmebaas ja failid).

### ISSUE THREAD

**Issue by KristjanVeensalu** [KristjanVeensalu/VeebiArendus#14]

**Comment by F1am3r** [comment]
Eelmise aasta töödel on lahendatud 2 pidi: plugin mis backupi teeb või läbi putty määrata kui tihti jooksutab scripti, mis teeb backupi

**Comment by F1am3r** [comment]
https://www.cloudways.com/blog/backup-woocommerce-store/  -  3 varianti.
